project:
  type: book

book:
  title: "temp change"
  author: "Jerell James"
  public-url: https://jerell.me/tempchange/
  repo-url: https://github.com/Jerell/tempchange
  repo-actions: [edit, issue]
  reader-mode: true
  date: "14/10/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

crossref:
  eq-prefix: Eq

date-modified: last-modified
